# fly.toml app configuration file generated for voilation-found-on-your-account on 2024-08-20T23:47:30+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voilation-found-on-your-account'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
